    environment: production
    chdir: ./
    pid: ./tmp/thin.pid 
    rackup: ./config/config.ru 
    log: ./log/thin.log 
    max_conns: 1024 
    timeout: 30 
    max_persistent_conns: 512 
    daemonize: true